name: docker-publish-ghcr

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  packages: write

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  docker_build_and_publish:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout turnilo"
        uses: actions/checkout@v4
        with:
          path: turnilo
          fetch-depth: 0
          fetch-tags: 1

      - name: "Set up QEMU"
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Container Registry (ghcr.io)"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and push to ghcr"
        run: |
          cd turnilo

          echo "Fix mess with tags in actions/checkout..."
          git fetch -f && git fetch -f --tags

          export TAG=$(git describe HEAD | sed 's/-.*$//g' | tr -d "v")
          export EXACT_TAG=$(git describe --exact-match --match "v*" || echo "")

          if [[ "${EXACT_TAG}" != "" ]]; then
            echo "Cross-building and PUSHING!"
            docker buildx build --platform ${PLATFORMS} --push -f Dockerfile . --tag ghcr.io/${GITHUB_REPOSITORY}:${TAG}
            docker buildx build --platform ${PLATFORMS} --push -f Dockerfile.bookworm . --tag ghcr.io/${GITHUB_REPOSITORY}:${TAG}-bookworm
          else
            echo "Cross-building ONLY"
            docker buildx build --platform ${PLATFORMS} -f Dockerfile .
            docker buildx build --platform ${PLATFORMS} -f Dockerfile.bookworm .
          fi
